### PR TITLE
feat: Support member wildcards in favorited searches

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

- [x] Refactor pattern parsing and make modular
- [x] Update favorites logic to retain the full, user-entered pattern
- [x] Resolve issue with `TypeError: Cannot read properties of undefined (reading 'direction')` when expanding favorited children

This PR separates the pattern parsing logic from the dataset search prompt and moves it into the `getDatasets` and `getChildren` functions in `ZoweDatasetNode`. This allows us to leverage member wildcards within favorited searches. It also ensures that the user's pattern submission is respected even after changes are made to data sets on the mainframe.

## Release Notes

Milestone: vNext

Changelog:

- Implemented support for favoriting a data set search that contains member wildcards. 
- Resolved `TypeError: Cannot read properties of undefined (reading 'direction')` error for favorited items.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] A GIF or screenshot is included in the PR for visual changes
- [x] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [x] There is coverage for the code that I have added
- [x] I have added new test cases and they are passing
- [x] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

**Comment by adam-wolfe** [comment]
I'm running into an issue when I add a favorite that contains a member filter with wildcards then try to expand the favorites (without reloading the window).

ZE-favorite-wildcard

After reloading the window, everything seems to work as expected.

**Comment by traeok** [comment]
Thanks for reporting this @adam-wolfe, the latest commit resolves this issue. 

I am a bit concerned that recent changes to `getSessionNode` have modified the behavior of pre-existing ZE features. I feel we should investigate our tree view functionalities to verify that they are still working as expected.

I've created an issue to track this request: #3073

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋 
Curious if some of the datasetTree private functions could be exported for ZE extenders to use in the future? 😋

**Review by JillieBeanSim — APPROVED** [review]
This works great! thanks @traeok for this addition

**Pull request merged**
