### PR TITLE
Update CLI dependency in ZE API

### PR DESCRIPTION
**Pull request by t1m0thyj**
## Proposed changes

Update CLI dependency in ZE API to fix https://github.com/zowe/zowe-cli/issues/2219

## Release Notes

Milestone: 2.18.0

Changelog: Updated the `@zowe/cli` dependency to fix error when using session with auth type "none"

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [ ] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [ ] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [ ] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @t1m0thyj

**Comment by t1m0thyj** [comment]
Updated CLI and other dependencies to use a semver range with a caret (`^`). This should make the ZE API package easier to maintain since we don't have to bump the version number every time there is a bug fix or security patch made to one of its dependencies such as the CLI package 🙂

**Review by traeok — APPROVED** [review]
Changes LGTM - thanks Timothy for updating the CLI & refining the version constraints 😋

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @t1m0thyj

**Pull request merged**
