### PR TITLE
chore: remove samples from `v2-lts` branch

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

- Use script to prepare Secrets SDK prebuilds instead of `copy-webpack-plugin`
  - Resolves issue where watch fails due to "busy" error when copying Windows prebuilds
- Removes samples from the `v2-lts` branch in favor of using the samples defined in [`zowe-client-samples`](https://github.com/zowe/zowe-client-samples)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [x] Other (please specify above in "Proposed changes" section)

### CODE REVIEW

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks @traeok!

**Review by zFernand0 — APPROVED** [review]
Thanks for removing! 🙏 
LGTM! 😋

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @traeok

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋 
I was wondering if we should've left the readme to direct people to the zowe-client-samples repo 😋 (if it didn't mess with any workflows/scripts) 😋

**Pull request merged**
