### PR TITLE
Prepare 3.0.3 release

### PR DESCRIPTION
**Pull request by JillieBeanSim**
## Proposed changes

updates lerna and changelogs for patch release

## Release Notes

Milestone: 3.0.3

Changelog: n/a

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [x] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [x] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [ ] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [ ] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

**Review by zFernand0 — DISMISSED** [review]
LGTM! 😋 

To make changelog reviews easier...

Zowe Explorer API
---
- Fixed an issue where the `responseTimeout` profile property was ignored for z/OSMF MVS and USS API calls. [#3225](https://github.com/zowe/zowe-explorer-vscode/issues/3225)


Zowe Explorer VSCE
---
- `DatasetFSProvider.stat()` will now throw a `FileNotFound` error for extenders trying to fetch an MVS resource that does not exist. [#3252](https://github.com/zowe/zowe-explorer-vscode/issues/3252)
- Fixed an issue where renaming or deleting a USS file or data set did not update the opened editor. [#3260](https://github.com/zowe/zowe-explorer-vscode/issues/3260)
- Fixed an issue during initialization where a broken team configuration file caused the "Show Config" action in the error dialog to stop working. [#3273](https://github.com/zowe/zowe-explorer-vscode/issues/3273)
- Fixed issue where switching the authentication methods would cause `Cannot read properties of undefined` error. [#3142](https://github.com/zowe/zowe-explorer-vscode/issues/3142)
- Fixed an issue where calling `vscode.workspace.fs.readFile` with a PDS member URI would throw an error when the PDS already existed as a filesystem entry. [#3267](https://github.com/zowe/zowe-explorer-vscode/issues/3267)
- Fixed issue where Zowe Explorer would present the "No configs detected" notification when initialized in a workspace without a Zowe team configuration. [#3280](https://github.com/zowe/zowe-explorer-vscode/issues/3280)
- Reduced the number of MVS API calls performed by `vscode.workspace.fs.readFile` when fetching the contents of a data set entry. [#3278](https://github.com/zowe/zowe-explorer-vscode/issues/3278)
- Fixed an issue to review inconsistent capitalization across translation strings. [#2935](https://github.com/zowe/zowe-explorer-vscode/issues/2935)
- Updated the test for the default credential manager for better compatibility with Cloud-based platforms such as Eclipse Che and Red Hat OpenShift Dev Spaces. [#3297](https://github.com/zowe/zowe-explorer-vscode/pull/3297)

**Comment by anaxceron** [comment]
> LGTM! 😋
> 
> To make changelog reviews easier...
> 
> ## Zowe Explorer API
> * Fixed an issue where the `responseTimeout` profile property was ignored for z/OSMF MVS and USS API calls. [#3225](https://github.com/zowe/zowe-explorer-vscode/issues/3225)
> 
> ## Zowe Explorer VSCE
> * `DatasetFSProvider.stat()` will now throw a `FileNotFound` error for extenders trying to fetch an MVS resource that does not exist. [#3252](https://github.com/zowe/zowe-explorer-vscode/issues/3252)
> * Fixed an issue where renaming or deleting a USS file or data set did not update the opened editor. [#3260](https://github.com/zowe/zowe-explorer-vscode/issues/3260)
> * Fixed an issue during initialization where a broken team configuration file caused the "Show Config" action in the error dialog to stop working. [#3273](https://github.com/zowe/zowe-explorer-vscode/issues/3273)
> * Fixed issue where switching the authentication methods would cause `Cannot read properties of undefined` error. [#3142](https://github.com/zowe/zowe-explorer-vscode/issues/3142)
> * Fixed an issue where calling `vscode.workspace.fs.readFile` with a PDS member URI would throw an error when the PDS already existed as a filesystem entry. [#3267](https://github.com/zowe/zowe-explorer-vscode/issues/3267)
> * Fixed issue where Zowe Explorer would present the "No configs detected" notification when initialized in a workspace without a Zowe team configuration. [#3280](https://github.com/zowe/zowe-explorer-vscode/issues/3280)
> * Reduced the number of MVS API calls performed by `vscode.workspace.fs.readFile` when fetching the contents of a data set entry. [#3278](https://github.com/zowe/zowe-explorer-vscode/issues/3278)
> * Fixed an issue to review inconsistent capitalization across translation strings. [#2935](https://github.com/zowe/zowe-explorer-vscode/issues/2935)
> * Updated the test for the default credential manager for better compatibility with Cloud-based platforms such as Eclipse Che and Red Hat OpenShift Dev Spaces. [#3297](https://github.com/zowe/zowe-explorer-vscode/pull/3297)

@JillieBeanSim -- I'd like to make the following edits to these changelog entries:

We should explain what `DatasetFSProvider.stat()` is: The `DatasetFSProvider.stat()` property/profile/whatever now throws a `FileNotFound` error for extenders trying to fetch an MVS resource that does not exist. 

We should add an indefinite articles here, and remove "the": Fixed an issue where switching authentication methods would cause a `Cannot read properties of undefined` error. 

We should add an indefinite articles here: Fixed an issue where Zowe Explorer would present the "No configs detected" notification when initialized in a workspace without a Zowe team configuration. 

We should define what `vscode.workspace.fs.readFile`is: Reduced the number of MVS API calls performed by the property/value/what `vscode.workspace.fs.readFile` when fetching the contents of a data set entry.

For more clarity: Fixed inconsistent capitalization across translation strings.

For more clarity: Updated the check for default credential managers for better compatibility with Cloud-based platforms such as Eclipse Che and Red Hat OpenShift Dev Spaces.

**Review by zFernand0 — APPROVED** [review]
Not sure if I'm allowed to approve, but LGTM! 😋

**Review by anaxceron — APPROVED** [review]
thank you @JillieBeanSim and @zFernand0!

**Comment by JillieBeanSim** [comment]
thanks @anaxceron & @zFernand0 

@t1m0thyj @traeok @adam-wolfe @likhithanimma1 @awharn @SanthoshiBoyina1 anyone find any issues testing?

**Comment by zFernand0** [comment]
Since the last commit only changed the lock file, the build wasn't triggered.
For a complete passing build, see the checks in:
- https://github.com/zowe/zowe-explorer-vscode/actions/runs/11895035079

**Review by traeok — APPROVED** [review]

**Review by likhithanimma1 — APPROVED** [review]

**Pull request merged**
