### PR TITLE
Generate NOTICE file for packages

### PR DESCRIPTION
**Pull request by JillieBeanSim**
## Proposed changes

Generate NOTICE file for packages, with NOTICE file header used from ZOWE CLI package from zowe.org/downloads [distribution](https://www.zowe.org/download)

can install new dependency into a package and run `pnpm run update-notices` to see the new package picked up and added to NOTICE file for the ZE package updated.  This command will be added to the release preparation and ran when new dependencies introduced into the packages having file changes verified then pushed into release PR along with lerna updates.

I do notice it doesn't add ZE API or our eslint-plugin with the SNAPSHOT in version, we will have to update that manually when command run for publishing.

adding Zowe package values manually where appropriate when missing after looking through files, all zowe packages will be updated for GA instances in release PR

## Release Notes

Milestone: v3 GA

Changelog: Generate NOTICE file for package.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [x] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [x] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [ ] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [ ] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

**Review by traeok — DISMISSED** [review]
Thanks for generating these Billie - I noticed there are some merge conflicts but everything LGTM!

**Review by t1m0thyj — COMMENTED** [review]
Thanks @JillieBeanSim for setting up the script to generate NOTICE files.

We discussed on standup yesterday about the possibility of using a common Zowe pipeline to generate the notices. Worked with @MarkAckert to enhance the same dependency scanner workflow that is used for CLI and we've added a new licenses artifact for VSCode. Would this work for attribution purposes?
* PR: https://github.com/zowe/zowe-dependency-scan-pipeline/pull/146
* Sample artifact: https://zowe.jfrog.io/ui/repos/tree/General/libs-snapshot-local/org/zowe/licenses/3.0.0-SNAPSHOT/zowe_licenses_vscode-3.0.0-SNAPSHOT-20240927164322.zip?clearFilter=true

**Comment by JillieBeanSim** [comment]
once we have our files `zowe_licenses_vscode.zip` included in the [artifactory](https://zowe.jfrog.io/ui/repos/tree/General/libs-release-local/org/zowe/licenses) we can close this PR

[PR](https://github.com/zowe/zowe-dependency-scan-pipeline/pull/149) to watch

**Comment by zFernand0** [comment]
Now that https://github.com/zowe/zowe-dependency-scan-pipeline/pull/149 was merged, are we good to close this PR? 🙏

**Comment by JillieBeanSim** [comment]
verified that our zip file is included in the 3.0.0 of [artifactory](https://zowe.jfrog.io/ui/repos/tree/General/libs-release-local/org/zowe/licenses/3.0.0)

**Pull request closed without merging**
