### PR TITLE
Removing icon names from translated strings

### PR DESCRIPTION
**Pull request by phaumer**
## Proposed changes

Several strings had icon names, e.g. menu items that show an icon on the left, embedded into the localized portion of the string. These references to the icon names then got translated by the machine translation, which broke the menu items.

## Release Notes

Milestone:

Changelog:

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [x] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [ ] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [ ] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

**Comment by phaumer** [comment]
Here are the updated translations for this PR: https://zowe.jfrog.io/artifactory/libs-snapshot-local/org/zowe/vscode/zowe-explorer-g11n/zowe-explorer-g11n-20241014-181610.zip

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks @phaumer for updating these strings and fixing some typos too!

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋 
I hope it wasn't too tedious to move the icons into the code 😋

**Comment by t1m0thyj** [comment]
> Here are the updated translations for this PR: https://zowe.jfrog.io/artifactory/libs-snapshot-local/org/zowe/vscode/zowe-explorer-g11n/zowe-explorer-g11n-20241014-181610.zip

Merging, updated translations have been uploaded to POEditor so the next ZE release will include them 🙂

**Comment by ROBIN-Olivier** [comment]
Hello @t1m0thyj , 
I use ZOWE 3.1.1, and some French translations are very bad.

October 15, 2024, you wrote: Merging, updated translations have been uploaded to POEditor so the next ZE release will include them.
In your file, it's much better.
For exemple:
- "copyName": "Copier le nom" is OK (Currently: "Nom de la copie")
- "hRecallDataSet": "Rappeler l'ensemble de données" is OK (Currently: "Ensemble de données de rappel"

In which version of ZOWE will it be made available?

furthermore, why have you translated PDS and JOBS ? This is the vocabulary used by the French. We are not talking about "Ensemble de données" or "Travail"...
Can we change this?
Thank you for your help:
Olivier

**Comment by ROBIN-Olivier** [comment]
No, really, these translations are disastrous...
Refresh job => Rafraichir l'emploi
Add to favorites => Le PDS est déjà contenu dans les favoris
Cancel Job => Annuler d'un travail
image

I work for two clients who use ZOWE, and we are looking into how to disable these translations.
Is there a solution?

**Comment by phaumer** [comment]
@ROBIN-Olivier thanks for the feedback. Could you try v3.2.0 and submit a new GitHub issue with a table for all the changes you are proposing? Cc/subscribe me in the issue as I am working with the translators.

To disable the localization you can switch VS Code to English with the instructions here: https://code.visualstudio.com/docs/configure/locales

**Comment by ROBIN-Olivier** [comment]
"To disable the localization you can switch VS Code to English with the instructions here"
i don't want to disable French Language from VSCode, but only from ZOWE !
since i was i child, i say "PDS" and "JOB" (and "chewing gum"), don't say "ENSEMBLE DE DONNEES" "TRAVAUX" (and "Gomme à macher") :-).
So, i will make a new post for that.

**Pull request merged**
