### PR TITLE
Clicking submitted job hyperlink throws error

### PR DESCRIPTION
**Pull request by SanthoshiBoyina**
## Proposed changes

To fix submitted job hyperlink throwing error

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by traeok — COMMENTED** [review]
I noticed that with these changes, the "node selection" changes to the session rather than the job that was submitted:

<details>
<summary>Before (v2.15.1 and below)</summary>
</summary>


</details>

<details>
<summary>After</summary>

</details>

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @SanthoshiBoyina for the fix, was there an open issue we can tie to the PR?

**Comment by SanthoshiBoyina** [comment]
> LGTM! thanks @SanthoshiBoyina for the fix, was there an open issue we can tie to the PR?

I had created a new issue [https://github.com/zowe/zowe-explorer-vscode/issues/2813](url)

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks @SanthoshiBoyina!

I don't have access to an RSE system, but tested that the hyperlinks work fine for both z/OSMF and zFTP profiles.

**Review by traeok — APPROVED** [review]
LGTM, thanks @SanthoshiBoyina!

**Review by awharn — APPROVED** [review]

**Pull request merged**
