### PR TITLE
No spool file available for active job

### PR DESCRIPTION
**Pull request by tiantn**
## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments
Fix issue #2832

### CODE REVIEW

**Review by traeok — CHANGES_REQUESTED** [review]
Hi @tiantn, thanks for looking into this issue!

Rather than changing the stepname on the default response, could we update `getSpoolFiles` to return an empty array whenever we cannot fetch spool files? This would be consistent with "no spool files available" and avoids adding special handling for this kind of response from the FTP extension. With the current changes, we'd have to add a check within Zowe Explorer's job tree to validate the `stepname`, which I'd like to avoid if possible.

**Comment by tiantn** [comment]
> Hi @tiantn, thanks for looking into this issue!
> 
> Rather than changing the stepname on the default response, could we update `getSpoolFiles` to return an empty array whenever we cannot fetch spool files? This would be consistent with "no spool files available" and avoids adding special handling for this kind of response from the FTP extension. With the current changes, we'd have to add a check within Zowe Explorer's job tree to validate the `stepname`, which I'd like to avoid if possible.

Thank you @traeok! I updated it to return an empty array.

**Review by JillieBeanSim — DISMISSED** [review]
LGTM! thanks @tiantn for this fix

**Comment by JillieBeanSim** [comment]
> @tiantn , I didn't try it yet, but wonder the empty array returned will make Zowe explorer shows nothing when user clicks to expand the active job, or Zowe explorer handled the empty array already, like showing a node with "No spool available"?

@std4lqi Zowe Explorer handles the empty array as successful API call with empty return and displays the node with "No spool available" as @traeok mentioned.

**Review by JillieBeanSim — DISMISSED** [review]

**Review by traeok — DISMISSED** [review]
Thanks for making that change @tiantn!

While I think this is the approach we should go with, it turns out that there's a bug in Zowe Explorer when returning an empty array for the spool files:

image

We handle empty lists in the Data Sets and USS tree, so we'll probably want to update the spool node logic for consistency.

To fix this we'll need to add a check in this `if` statement in the ZoweSpoolNode constructor, on line 421:
https://github.com/zowe/zowe-explorer-vscode/blob/f415f3820f92e3e8f81bd88a3e997f388c25418a/packages/zowe-explorer/src/job/ZoweJobNode.ts#L421-L426

Instead of `opts.parentNode && opts.parentNode.getParent()`, can you please update this check to `opts.spool && opts.parentNode && opts.parentNode.getParent()`?

Thanks!

**Comment by JillieBeanSim** [comment]
we have [handling in ZE](https://github.com/zowe/zowe-explorer-vscode/blob/f415f3820f92e3e8f81bd88a3e997f388c25418a/packages/zowe-explorer/src/job/ZoweJobNode.ts#L134) for the empty array with the spool.length check displaying "There are no JES spool messages to display" for the empty array of spool files for job

**Comment by traeok** [comment]
> we have [handling in ZE](https://github.com/zowe/zowe-explorer-vscode/blob/f415f3820f92e3e8f81bd88a3e997f388c25418a/packages/zowe-explorer/src/job/ZoweJobNode.ts#L134) for the empty array with the spool.length check displaying "There are no JES spool messages to display" for the empty array of spool files for job

While we do handle that scenario in `getChildren`, the `ZoweSpoolNode` constructor will still try to call `encodeJobFile` with an undefined spool object - this causes the error message above to appear when calling `getChildren` on the active job.

**Comment by tiantn** [comment]
> > we have [handling in ZE](https://github.com/zowe/zowe-explorer-vscode/blob/f415f3820f92e3e8f81bd88a3e997f388c25418a/packages/zowe-explorer/src/job/ZoweJobNode.ts#L134) for the empty array with the spool.length check displaying "There are no JES spool messages to display" for the empty array of spool files for job
> 
> While we do handle that scenario in `getChildren`, the `ZoweSpoolNode` constructor will still try to call `encodeJobFile` with an undefined spool object when constructing the placeholder node - this causes the error message above to appear when calling `getChildren` on the active job.
> 
> Since the issue is specific to Zowe Explorer's core logic, I don't mind pushing the fix to this PR, but I wanted to mention this first before doing so. Whatever works best for @tiantn works for me - I can pull and test the change once it's added, or I can push up the necessary changes to get this merged 😁

Thank you @traeok , @JillieBeanSim , I am not very familiar with Zowe Explorer's core logic. But if any thing I can do please let me know. 😄

**Comment by traeok** [comment]
> Thank you @traeok , @JillieBeanSim , I am not very familiar with Zowe Explorer's core logic. But if any thing I can do please let me know. 😄

No worries @tiantn, I've pushed up a small change to this PR that will fix the behavior I mentioned - hope that's okay 😋 
Thanks again for the fix!

**Review by std4lqi — APPROVED** [review]

**Review by zFernand0 — COMMENTED** [review]
Changes LGTM! 😋 

Do we need to update the FTP dependency to 2.1.9?

**Pull request merged**
