### PR TITLE
Unable to open Favorited Job Search

### PR DESCRIPTION
**Pull request by SanthoshiBoyina1**
## Proposed changes

To add the ability to open a Favorited Job Search under Favorites and as well as when the extension is reloaded.

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by traeok — COMMENTED** [review]
Hi @SanthoshiBoyina1, thanks for fixing this behavior! Just as a heads up, this is already in place in v3 so no need to port it over 👍 

Will approve after a changelog entry is added 😁

**Review by JillieBeanSim — COMMENTED** [review]
Hey @SanthoshiBoyina1 thanks for tackling this item, I do see a broken unit test suite as well on this PR.  Functionality looks good so once mentioned items are address this should be good to go 😄

**Review by traeok — APPROVED** [review]

**Review by JillieBeanSim — APPROVED** [review]
Thanks @SanthoshiBoyina1  LGTM

**Comment by zFernand0** [comment]
Hey @traeok and @JillieBeanSim,
Should this be ported to vNext?

https://github.com/zowe/zowe-explorer-vscode/blob/next/packages/zowe-explorer/src/trees/job/ZoweJobNode.ts#L125

**Comment by JillieBeanSim** [comment]
@zFernand0, @traeok mentions in a comment that it is not needed on next branch

**Comment by traeok** [comment]
@zFernand0 That line points to the placeholder node that we show when expanding a profile in the Jobs tree w/o a filter, so that should be okay. I've made some adjustments in PR #2827 to address this specific case, so I don't believe this needs to be ported 👍

**Comment by zFernand0** [comment]
😓 I should've read the whole history of the PR before going through the code.
My apologies.

And thanks for clarifying 🙏🏽

**Comment by JillieBeanSim** [comment]
> 😓 I should've read the whole history of the PR before going through the code. My apologies.
> 
> And thanks for clarifying 🙏🏽

No worries, thanks for double checking.  Better than it slipping through 😄

**Pull request merged**
