### PR TITLE
Remove check for parent entry when calling DatasetFSProvider.readFile()

### PR DESCRIPTION
**Pull request by benjamin-t-santos**
## Proposed changes

DatasetFSProvider.readFile() will not fetch a data set or member if its parent's entry exists. This is fine if you are using the tree views, but it causes extenders calling readFile() to fetch their resources (see https://github.com/zowe/zowe-explorer-vscode/issues/3267).

The proposed change is removing this check for the parent's entry. Now, if the data set/member does exist, `remoteLookupForResource()` will return without making any API calls to the remote host and just return the value of `this.lookup(uri)`. If the data set/member does exist, `remoteLookupForResource()` will fetch it and create an entry for it.

## Release Notes

- `DatasetFSProvider.readFile()` no longer throws `FileNotFound` errors when requesting members or data sets for the first time when their parent has already been fetched. [#3267](https://github.com/zowe/zowe-explorer-vscode/issues/3267)

Milestone:

Changelog:

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] All PR dependencies have been merged and published (if applicable)
- [x] A GIF or screenshot is included in the PR for visual changes
- [x] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [ ] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [ ] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

**Comment by benjamin-t-santos** [comment]
Not sure about these changes to the l10n bundles. They were generated when I ran the `prepublish` command...

**Comment by traeok** [comment]
My apologies @benjamin-t-santos as I did not realize that you were working on a fix. #3268 should have the similar changes but with the other test updated to match the expected behavior instead of removed.

I can close my PR if preferred 🙂

**Comment by benjamin-t-santos** [comment]
They look to be the same but your has better tests 🙂 I should have checked first. Closing this one.

**Comment by traeok** [comment]
No worries. Thanks again for your help w/ diagnosing and resolving these cases.

**Comment by benjamin-t-santos** [comment]
No problem. The v3 file system is very good. I know these changes cover some specific edge cases for extenders so I appreciate you guys working with me.

**Pull request closed without merging**
