### PR TITLE
3.0.0 Pre-release Aug 2024

### PR DESCRIPTION
**Pull request by JillieBeanSim**
## Proposed changes

Prepare v3 pre-release with breaking changes

- [x] need missing changelog about breaking change in [PR](https://github.com/zowe/zowe-explorer-vscode/pull/3019)
- [x] review other changelogs for clarity
- [x] make sure v3 extender wiki has all breaking changes listed
  - think I have all updates https://github.com/zowe/zowe-explorer-vscode/wiki/v3-Changes-for-Users-and-Extenders

## Release Notes

Milestone: 3.0.0 pre-release

Changelog:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [x] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [ ] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [ ] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [ ] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

**Comment by JillieBeanSim** [comment]
Making ready for review, wiki updates don't affect the release but will work on making sure it's updated.  @t1m0thyj would you mind pushing a CHANGELOG for [PR's](https://github.com/zowe/zowe-explorer-vscode/pull/3019) breaking change please?

**Comment by t1m0thyj** [comment]
> Making ready for review, wiki updates don't affect the release but will work on making sure it's updated. @t1m0thyj would you mind pushing a CHANGELOG for [PR's](https://github.com/zowe/zowe-explorer-vscode/pull/3019) breaking change please?

I plan to open a quick PR against vNext branch to fix an issue we found with "Log out of authentication service", and will update the changelog too 🙂

**Review by zFernand0 — APPROVED** [review]
I believe we should run the `pnpm update-sdks` script to get the audit fixed before we merge this PR 😋 

LGTM! 😋

**Review by zFernand0 — APPROVED** [review]

**Review by zFernand0 — DISMISSED** [review]

**Comment by traeok** [comment]
I pushed up a quick fix that is a part of #3067 - since the fix will be merged regardless of which PR goes in first, no need to open a separate one 😋

**Comment by JillieBeanSim** [comment]
> I pushed up a quick fix that is a part of #3067 - since the fix will be merged regardless of which PR goes in first, no need to open a separate PR 😋

we can push another pre-release before and after the code freeze, sounds like there may be a few more breaking changes 😄

**Review by zFernand0 — DISMISSED** [review]

**Review by traeok — DISMISSED** [review]
Tested and LGTM. Thanks @JillieBeanSim for preparing the pre-release

---

Do we want to go ahead and merge this, or do we want to get an additional 1-2 reviews?
Personally, I'm okay with merging and moving forward with the pre-release, but it might help to get an extra tester to verify that the pre-release is working smoothly across our dev machines. I personally didn't encounter any issues, but haven't exhausted every feature's use case during testing.

**Review by t1m0thyj — DISMISSED** [review]

**Review by traeok — APPROVED** [review]

**Review by t1m0thyj — APPROVED** [review]

**Pull request merged**
