### PR TITLE
fix(v3): Not including extenders in Team config during creation

### PR DESCRIPTION
**Pull request by likhithanimma1**
## Proposed changes

Solves #3122 
Fix bug regarding extender profiles not being added to the config file during creation.

## Release Notes

Milestone:

Changelog: Fix issue with extender profiles not being included in fresh team configuration file. [#3122]

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [ ] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [x] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [ ] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

**Review by traeok — COMMENTED** [review]
Hi Likhitha, this looks great and the fix makes sense to me. Thanks for looking into this!
I'm wondering if we'll want to add a unit test to make sure that the extender types are being passed in to `imperative.ConfigBuilder.build`? This way we can verify that Imperative receives all the type configurations when building the config.

**Comment by likhithanimma1** [comment]
> Hi Likhitha, this looks great and the fix makes sense to me. Thanks for looking into this! I'm wondering if we'll want to add a unit test to make sure that the extender types are being passed in to `imperative.ConfigBuilder.build`? This way we can verify that Imperative receives all the type configurations when building the config.

Added unit test @traeok :)

**Review by traeok — APPROVED** [review]
Tested with the FTP extension and the config/schema includes the extender types as expected. Thanks Likhitha for the fix!

**Review by adam-wolfe — APPROVED** [review]
LGTM, thanks @likhithanimma1

**Pull request merged**
