### PR TITLE
fix(uss): Support "Pull from Mainframe" w/ binary files

### LINKED ISSUE #3355: ze(uss): `Pulling from mainframe` status bar message does not get disposed of for binary files
**Describe the bug**

The status bar message doesn't go away when you open a USS file as binary and then pull from mainframe
image

**To Reproduce**

1. Open a USS file as binary (via the open with encoding option)
2. Right click on the same file and `Pull from mainframe`
3. Notice the status bar message not getting disposed of.
image

**Expected behavior**

For the message to go away eventually 😋 

**Screenshots**

image

**Desktop (please complete the following information):**

- OS: All
- Zowe Explorer Version: 3.0.3
- (Optional) Zowe CLI Version: N/A
- (Optional) Are you using Secure Credential Store? N/A

**Additional context**

Found while looking for a Download option for USS files and Dataset.
Thanks @roman-kupriyanov

---

Since the node's contextValue is `binaryFile`, the `SharedContext.isDocument()` doesn't consider it as a valid document. Thus we remove it from the list.
image

I think we just need to dispose of the status message outside the for-loop
image

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

Fixes #3355 

## Release Notes

Milestone: 3.1.0

Changelog:

- Fixed an issue where binary USS files were not fetched using the "Pull from Mainframe" context menu option. [#3355](https://github.com/zowe/zowe-explorer-vscode/issues/3355)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] All PR dependencies have been merged and published (if applicable)
- [x] A GIF or screenshot is included in the PR for visual changes
- [x] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [x] There is coverage for the code that I have added
- [x] I have ~added new~ updated test cases and they are passing
- [x] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

**Review by anaxceron — APPROVED** [review]

**Review by JillieBeanSim — COMMENTED** [review]
Hey @traeok thanks for working on this bugfix.

I do notice I don't get the status bar notification of fetching USS file when pulling from mainframe with binary, but do with non-binary.  Is this expected or should we be seeing this status message in both scenarios?

**Comment by traeok** [comment]
> Hey @traeok thanks for working on this bugfix.
> 
> I do notice I don't get the status bar notification of fetching USS file when pulling from mainframe with binary, but do with non-binary. Is this expected or should we be seeing this status message in both scenarios?

I looked into it some more and it turns out that "Pull from Mainframe" never supported binary USS files. You should now see the status bar with binary files. I also need to port this back to v2.

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋

**Review by JillieBeanSim — APPROVED** [review]
Thanks @traeok for looking into that, all LGTM 😄

**Pull request merged**
