### PR TITLE
Port various dependabot PRs and 2828 to next

### PR DESCRIPTION
**Pull request by JillieBeanSim**
## Proposed changes

Porting:
- https://github.com/zowe/zowe-explorer-vscode/pull/2828
- https://github.com/zowe/zowe-explorer-vscode/pull/2818
- https://github.com/zowe/zowe-explorer-vscode/pull/2819
- https://github.com/zowe/zowe-explorer-vscode/pull/2842
- https://github.com/zowe/zowe-explorer-vscode/pull/2845
- https://github.com/zowe/zowe-explorer-vscode/pull/2844
- https://github.com/zowe/zowe-explorer-vscode/pull/2843
- https://github.com/zowe/zowe-explorer-vscode/pull/2846

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by JillieBeanSim** [comment]
seeing this with pnpm install about deprecated subdependencies on this branch, don't think it's on next

Screenshot 2024-05-02 at 9 05 15 AM

**Review by zFernand0 — APPROVED** [review]

**Comment by zFernand0** [comment]
> seeing this with pnpm install about deprecated subdependencies on this branch, don't think it's on next
> 
> Screenshot 2024-05-02 at 9 05 15 AM


Hey Billie,

I tried reproducing the warnings locally, but no success. 
I'm afraid I also don't seem them as part of the builds (`win, lin, mac X n18, n20`)

Could you try a fresh-clone? 
- `pnpm fresh-clone && pnpm install`

Also, what version of PNPM do you have installed? (`pnpm --version`)

**Review by traeok — APPROVED** [review]
Looks good to me, thanks @JillieBeanSim 

I tried `pnpm install && pnpm build` with fresh `node_modules` - no issues here 🙂

**Review by t1m0thyj — APPROVED** [review]
@JillieBeanSim I see the same warning when installing the `next` branch, so I don't think it's anything introduced by this PR:
image

**Pull request merged**
