### PR TITLE
release: `v2.18.0`

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

Prepares `main` for release automation to publish `v2.18.0`.

## Checklist

**General**

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] All PR dependencies have been merged and published (if applicable)

### CODE REVIEW

**Comment by t1m0thyj** [comment]
Should we try to merge https://github.com/zowe/zowe-explorer-vscode/pull/3064 before release?

**Comment by JillieBeanSim** [comment]
> Should we try to merge #3064 before release?

Hey @t1m0thyj I see the PR is in draft, what is ETA for review readiness?

**Comment by t1m0thyj** [comment]
> Hey @t1m0thyj I see the PR is in draft, what is ETA for review readiness?

I would expect by EoD Monday. The bug is not a regression as we noticed it in 2.17 as well, but might be deemed as high severity.

**Comment by JillieBeanSim** [comment]
Seeing issues downloading spool files with zosmf profile (all & single) 
Screenshot 2024-08-26 at 9 32 54 AM
Screenshot 2024-08-26 at 9 32 12 AM

**Comment by awharn** [comment]
I appear to be able to download spool through z/OSMF, but if I create a new config and give it my username and password, the other tree nodes for the same profile are not updated and are prompting for the credentials as well.

**Comment by JillieBeanSim** [comment]
> I appear to be able to download spool through z/OSMF, but if I create a new config and give it my username and password, the other tree nodes for the same profile are not updated and are prompting for the credentials as well.

it may be related to the follow up error I got when attempting to cancel, and I did change credentials before these steps. Sounds like old cached info in jobs tree for profile.
Screenshot 2024-08-26 at 9 44 12 AM

**Review by adam-wolfe — DISMISSED** [review]
I am seeing issues when a user has a team config that contains a json error.

Issue 1:
1. Start with a good config.
2. Launch VS Code.
3. Edit the config and introduce a json error (e.g., add a bracket)
4. Right click on a profile in the trees, select Manage Profile, then select Edit Profile. (the same behavior will also occur if you try to search for data sets)
5. You will receive an error that says you have a json error, but you won't be shown your team config.

This happens in 2.17 as well.

Issue 2 (new to 2.18):
1. Start with a config that contains a json error.
2. Launch VS Code.
3. You will get an error message saying that you have a json error in your team config.
4. Click the + button to add a profile to one of the trees.
5. You will get an error message: `Error running command zowe.ds.addSession: command 'zowe.ds.addSession' not found. This is likely caused by the extension that contributes zowe.ds.addSession.`

In 2.18, you are never given the option to "Show config" if you launch VS Code with a team config that contains an error.

**Review by JillieBeanSim — COMMENTED** [review]
I can confirm the issues I had experienced previously are a cache issue and I believe it's addressed in v3 with the Event handlers.  After pulling in the latest from main I do get the JSON error when saving an error in the config file but I do also experience the failure to initialize ZE if VS Code is started with errors in the config JSON.

**Review by t1m0thyj — COMMENTED** [review]
LGTM once #3082 is merged 😋

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋 

We should be good to release by Thursday if we don't find any showstoppers 😋

**Review by JillieBeanSim — APPROVED** [review]

**Comment by zFernand0** [comment]
One thing to note is that the console/terminal will not work unless the session/profile is loaded in a tree and has been validated.
image

This could be addressed as a bug fix later on if we have many people running into this behavior. 😋

**Pull request merged**
