### PR TITLE
v2.15.3 Release

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

Updates `lerna.json` version to v2.15.3 to release the new patch.

### CODE REVIEW

**Comment by traeok** [comment]
Outstanding PRs that are candidates for maintenance:

- #2828 (would need rebased though, might be best to save for 2.16)
- #2858

**Comment by JillieBeanSim** [comment]
> Outstanding fixes and PRs that are potential candidates for the patch:
> 
> * [fix: duplicated profile schema writing on repeated team config init #2828](https://github.com/zowe/zowe-explorer-vscode/pull/2828)
>   
>   * this branch would need rebased to get it in 2.15.3 - it might be best to save this for 2.16
> * [Port: Bump semver from 7.0.0 to 7.6.0 #2858](https://github.com/zowe/zowe-explorer-vscode/pull/2858)

Thanks for preparing the release PR @traeok, I think #2828 can stay against main and be part of 2.16.0 😄

**Comment by traeok** [comment]
> > Outstanding fixes and PRs that are potential candidates for the patch:
> > 
> > * [fix: duplicated profile schema writing on repeated team config init #2828](https://github.com/zowe/zowe-explorer-vscode/pull/2828)
> >   
> >   * this branch would need rebased to get it in 2.15.3 - it might be best to save this for 2.16
> > * [Port: Bump semver from 7.0.0 to 7.6.0 #2858](https://github.com/zowe/zowe-explorer-vscode/pull/2858)
> 
> Thanks for preparing the release PR @traeok, I think #2828 can stay against main and be part of 2.16.0 😄

No problem! Sounds good to me 😅👍

**Review by JillieBeanSim — APPROVED** [review]

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋

**Pull request merged**
