### PR TITLE
fix: formatting of 401 error message

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

This won't need ported for 3.0.3 as this was a side effect of the error correlator

### How to test

Same steps as in #3302:

- Checkout this branch in the repo with VS Code opened
- `pnpm install && pnpm build`
- After the build has finished, click on the Run & Debug panel on the VS Code Side Bar
- Select "Run VS Code Extension" from the tasks list at the top and select the Play ▶ button
- Once opened, make sure that you have (or set) valid credentials on a profile in ZE
- Execute a search on that profile and expand a folder so that a file/PDS member/spool item is visible
- Before opening the file, right click on your profile -> "Manage Profile" -> "Update Credentials"
- Enter in invalid credentials. I recommend using a fake username to prevent lockouts
- Once finished, try to open the file. Notice the error in the editor appears but you are prompted to update your credentials.

Except this time, you'll see a nicer error message 😋

## Release Notes

Milestone: 3.0.3

Changelog: No changelog since fix hasn't been published yet

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [ ] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [ ] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [ ] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

**Review by JillieBeanSim — CHANGES_REQUESTED** [review]
thanks for looking into this issue some more @traeok. I am not seeing the 401 pop up message with these changes.  I am getting an action bar across the top of the text editor file that just continues to run like the request is hanging.

**Comment by traeok** [comment]
> thanks for looking into this issue some more @traeok. I am not seeing the 401 pop up message with these changes. I am getting an action bar across the top of the text editor file that just continues to run like the request is hanging.

No problem @JillieBeanSim, thanks for testing. Do you happen to have the steps for reproducing this issue? I know that there are still some scenarios where the 401 pop up will not occur, but per our discussion about prompting in standup, that will need resolved separately as part of #3329. This PR only changes the error message and not the behavior of the prompt itself.

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks @traeok!

**Review by zFernand0 — APPROVED** [review]
Changes LGTM! 😋 

I do agree that there may be some specific scenarios where "401 pop-up prompts" don't show (#3329) which we can address

**Pull request merged**
