### PR TITLE
merge: 2.16 changes -> `maintenance`

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

Merges the recent changes from `main` into `maintenance`.

TODO:
- [x] Merge and include https://github.com/zowe/zowe-explorer-vscode/pull/2802
- [ ] Merge and include https://github.com/zowe/zowe-explorer-vscode/pull/2867

### CODE REVIEW

**Comment by JillieBeanSim** [comment]
@traeok if this is in prep of 2.16.0 code freeze, can this be changed to a draft until the PRs against main for 2.16.0 are merged and this is updated with all?

**Comment by zFernand0** [comment]
Dumb question: 
If main is up to date with maintenance, why not just remove+recreate (or rebase) the maintenance branch?

**Review by zFernand0 — COMMENTED** [review]
Changes LGTM! :yum: 
just waiting on the last few PRs in the 2.16.0 (`-> main`) to be merged before approving 😋

**Comment by traeok** [comment]
> Dumb question: If main is up to date with maintenance, why not just remove+recreate (or rebase) the maintenance branch?

I would be in favor of rebasing or removing/recreating `maintenance`, but wasn't sure if the squad would be okay with that, so I went with the usual merge process this time around 👍

**Review by t1m0thyj — DISMISSED** [review]

**Review by JillieBeanSim — APPROVED** [review]

**Review by t1m0thyj — APPROVED** [review]

**Review by JillieBeanSim — APPROVED** [review]

**Pull request merged**
