### PR TITLE
Fix infinite loop when fetching USS resources with stat()

### PR DESCRIPTION
**Pull request by benjamin-t-santos**
## Proposed changes

Extenders can fetch a USS resource on demand using `vscode.workspace.fs.stat()` with the `fetch=true` query. When done with a USS file that has not expanded in the USS tree view, Zowe Explorer gets stuck in an infinite loop of calling `stat()` over and over again. Here's how it happens:

1. `vscode.workspace.fs.stat()` is called for a USS resource with the fetch query set to true. Example: `vscode.workspace.fs.stat(zowe-uss:/zosmf/user/test.txt)`
2. `UssFSProvider.remoteLookupForResource()` is called to fetch the file from the host.
3. This eventually calls `UssFSProvider.fetchEntries()`. `fetchEntries()` checks if the parent directory of the requested file is in the file system. If it's not, `await vscode.workspace.fs.createDirectory(parentUri)` is called on line 191 to create it.
4. `stat()` is called again for the `parentUri` with a `fetch=true` query as a result of calling `vscode.workspace.fs.createDirectory()`. (I believe this is due to the VS Code file system base implementation. It surprised me but looking at the call stack that is what I see)
5.  `UssFSProvider.remoteLookupForResource()` is called to fetch the directory from the host. This eventually calls `UssFSProvider.fetchEntries()`
6. When `listFiles()` is called in `fetchEntries()`, if the resource requested is a directory that does not already exist in the file system, we call `vscode.workspace.fs.createDirectory()` with the directory's URI. This is the same exact URI that is used when calling `createDirectory()` in step 3. 

Basically, Zowe Explorer keeps calling `vscode.workspace.fs.createDirectory()` for the parent of the requested file over and over again without ever resolving. This does not happen when using tree views because of how directories are expanded from the top-down. In this case, I as an extender am requesting a file from a parent directory that has not been created.

There are improvements we can make to improve the `UssFSProvider` for extenders, but with the goal of trying to get a fix for this issue into the v3.0.3 release, I tried to keep my changes minimal. I added code that sets the query of the `parentUri` to an empty string when calling `vscode.workspace.fs.createDirectory()` in `fetchEntries()`. This prevents it from entering the infinite loop by not trying to fetch the requested resource's parent.

This change will not impact the tree view, as those views do not make use of the fetch query. This change will only fix functionality for extenders.

## Release Notes

Milestone:

Changelog: 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [ ] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [ ] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [ ] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

**Review by traeok — APPROVED** [review]
Thanks for catching this Benjamin, the fix is much appreciated. I tested this with a basic sample extension and the fix looks good to me. Please disregard the failing `ze-build (22.x, ubuntu-22.04)` check as its unrelated.

---

It seems that the `vscode.workspace.fs` wrappers perform some extra checks before creating the directory - my guess is that they probably `stat` the folder to make sure it doesn't exist before trying to create it. When calling `createDirectory` directly within the providers, this step doesn't occur, so the infinite loop isn't encountered. 

Admittedly, the `stat` function has caused more grief than expected with the file system provider implementations, especially when it comes to network requests. I also did not expect VS Code to call it as much as it does, and this particular case seems to be a side effect of preserving the `fetch` query on the original URI  😵‍💫

**Comment by benjamin-t-santos** [comment]
@traeok Thanks for the review. Is it possible to include this fix in the v3.0.3 release?

**Comment by JillieBeanSim** [comment]
> @traeok Thanks for the review. Is it possible to include this fix in the v3.0.3 release?

@zFernand0 @t1m0thyj @adam-wolfe what do y'all think too? I believe we are including a similar fix for another tree.

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks @benjamin-t-santos!

**Comment by t1m0thyj** [comment]
> @zFernand0 @t1m0thyj @adam-wolfe what do y'all think too? I believe we are including a similar fix for another tree.

@JillieBeanSim This fix looks like a simple one that would be good to include 👍

**Comment by JillieBeanSim** [comment]
thanks I will get it ported

**Pull request merged**
