### PR TITLE
Add progress indicator to mvs view for filterPrompt

### LINKED ISSUE #2181: Long delay before activity indicator is displayed after applying a dataset filter
**Describe the bug**

With certain mainframe connections, there can be a long delay before the activity indicator/loading bar is displayed when applying a filter. This delay can be so long that it seems like something has gone wrong.

**To Reproduce**

This was tested on the mainframe used for the IBM Z Xplore program. I filtered datasets using my userid.

**Expected behavior**

The loading bar should appear as soon as possible after the user hits enter when applying a filter.

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS 13.2.1
- Zowe Explorer Version: 2.6.2

### PR DESCRIPTION
**Pull request by JillieBeanSim**
## Proposed changes

resolves #2181 

## Release Notes

Milestone: 2.16.0

Changelog: Updated MVS view progress indicator for entering a filter search. [#2181](https://github.com/zowe/zowe-explorer-vscode/issues/2181)

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by adam-wolfe — APPROVED** [review]
LGTM. Thanks @JillieBeanSim

**Review by traeok — CHANGES_REQUESTED** [review]
This looks great @JillieBeanSim! I love the new progress bar UX - but, could we wait until the API request is sent to the server before showing the progress bar? Otherwise, it will appear while a user types out a filter, which is a bit misleading as no requests are made until the filter selection is confirmed/submitted.

**Comment by JillieBeanSim** [comment]
> This looks great @JillieBeanSim! I love the new progress bar UX - but, could we wait until the API request is sent to the server before showing the progress bar? Otherwise, it will appear while a user types out a filter, which is a bit misleading as no requests are made until the filter selection is confirmed/submitted.

@traeok if you test this with marketplace you can see that the tree view does have an indicator when the fetch api call is made.  The issue stated is that some systems with slower connections take a long time before seeing that indicator leaving the user wondering if anything is happening. Having the indicator wrap the entire call, since a lot is going on here not even counting the fetch request, lets the user know there is something happening in that particular tree view after selecting the magnifying glass.

**Comment by traeok** [comment]
> > This looks great @JillieBeanSim! I love the new progress bar UX - but, could we wait until the API request is sent to the server before showing the progress bar? Otherwise, it will appear while a user types out a filter, which is a bit misleading as no requests are made until the filter selection is confirmed/submitted.
> 
> @traeok if you test this with marketplace you can see that the tree view does have an indicator when the fetch api call is made. The issue stated is that some systems with slower connections take a long time before seeing that indicator leaving the user wondering if anything is happening. Having the indicator wrap the entire call, since a lot is going on here not even counting the fetch request, lets the user know there is something happening in that particular tree view after selecting the magnifying glass.

I see, thanks for clarifying. I can reproduce that behavior, even though my test system is quick enough that it isn't as obvious. 
For testing, I was looking for the expected behavior mentioned in the issue:

> **Expected behavior**
> The loading bar should appear as soon as possible after the user hits enter when applying a filter.

I think it would be nice to show some loading indicator when clicking the search icon and before the input box appears - but, users might look to the top of the tree view for this same "bar indicator" once submitting their filter to know that the request is in progress. Showing the same indicator when clicking the search button would change the behavior of the progress bar and might catch users off-guard, so that's something to consider.

If we wrap [these lines](https://github.com/zowe/zowe-explorer-vscode/blob/d681a051f4c41bc2014e79ef2d4c1cc191264ef1/packages/zowe-explorer/src/dataset/DatasetTree.ts#L1028-L1033) with the `Gui.withProgress` call, it will show the progress bar after as the filter is placed and once the request has started. Looking around at the code in v2, we use tree view's built-in behavior to show the progress bar after the request takes some time, which could explain the delay before the progress bar appears.

**Review by traeok — APPROVED** [review]
Sorry for the delayed follow-up, but this LGTM! Thanks for the bug fix @JillieBeanSim 😅

**Pull request merged**
