### PR TITLE
Fix ZE activation and commands failing when team config contains JSON error

### LINKED ISSUE #3074: ZE activation and commands fail when team config contains JSON error
> I am seeing issues when a user has a team config that contains a json error.
>
> Issue 1:
> 1. Start with a good config.
> 2. Launch VS Code.
> 3. Edit the config and introduce a json error (e.g., add a bracket)
> 4. Right click on a profile in the trees, select Manage Profile, then select Edit Profile. (the same behavior will also occur if you try to search for data sets)
> 5. You will receive an error that says you have a json error, but you won't be shown your team config.
> 
> This happens in 2.17 as well.
> 
> Issue 2 (new to 2.18):
> 1. Start with a config that contains a json error.
> 2. Launch VS Code.
> 3. You will get an error message saying that you have a json error in your team config.
> 4. Click the + button to add a profile to one of the trees.
> 5. You will get an error message: `Error running command zowe.ds.addSession: command 'zowe.ds.addSession' not found. This is likely caused by the extension that contributes zowe.ds.addSession.`
> 
> In 2.18, you are never given the option to "Show config" if you launch VS Code with a team config that contains an error.

_Originally posted by @adam-wolfe in https://github.com/zowe/zowe-explorer-vscode/pull/3063#pullrequestreview-2264417842_

### PR DESCRIPTION
**Pull request by t1m0thyj**
## Proposed changes

Fixes #3074

## Release Notes

Milestone: 2.18.0

Changelog: Fixed JSON errors being ignored when `zowe.config.json` files change on disk and are reloaded

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [ ] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [ ] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [ ] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

**Review by JillieBeanSim — COMMENTED** [review]
Thanks for jumping on this so quickly @t1m0thyj 
I do still experience issue 1, I do get the popup after saving a config with invalid JSON but if I close that pop up and close the file then try to do filter search I only get the parsing error without option to open config.
Screenshot 2024-08-28 at 10 47 14 AM

**Comment by t1m0thyj** [comment]
> Thanks for jumping on this so quickly @t1m0thyj I do still experience issue 1, I do get the popup after saving a config with invalid JSON but if I close that pop up and close the file then try to do filter search I only get the parsing error without option to open config. Screenshot 2024-08-28 at 10 47 14 AM

Good catch @JillieBeanSim - should be fixed in https://github.com/zowe/zowe-explorer-vscode/pull/3075/commits/03c17742234f5f18310d752659b8c394898f77cb 😁

**Review by JillieBeanSim — DISMISSED** [review]
LGTM! thanks @t1m0thyj

**Review by traeok — CHANGES_REQUESTED** [review]
Thanks for looking into a solution for this @t1m0thyj!

I noticed that if I make an error in my Zowe config and save it, these 2 info messages appear:

image

If I close my config in the open editor and click on the "Show Config" option at this moment, it works successfully. 

However, if I close VS Code and make the change in another editor, the same messages appear when I open VS Code but the "Show Config" button no longer works.

**Review by traeok — APPROVED** [review]
LGTM! Thanks for updating the "Show Config" logic to point out the error in the editor, I'm sure users will appreciate that 😋

**Review by adam-wolfe — APPROVED** [review]
LGTM, thanks @t1m0thyj

**Pull request merged**
