### PR TITLE
Update release.config.js to set channel for prerelease build

### PR DESCRIPTION
**Pull request by t1m0thyj**
## Release Notes

Milestone:

Changelog:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [ ] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [ ] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [ ] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

**Review by JillieBeanSim — COMMENTED** [review]
should this be against main first or is the release/3.* branch ok?

**Review by traeok — APPROVED** [review]

**Comment by traeok** [comment]
> Thanks for helping with the deployment failures @t1m0thyj, should this be against main first or is the release/3.* branch ok?

@JillieBeanSim We'll probably want to double-check w/ Timothy before merging, but I think this should be fine. Octorelease uses the branch name if a channel name is not provided for a pre-release. The publishing failed because lerna tried to publish as `3.0.0/release-3.0.0/pre-release.{snapshot-date}` instead of `3.0.0-next.{snapshot-date}` due to the missing channel. Adding `next` as the channel will make it respect our usual versioning format for snapshots.

**Review by JillieBeanSim — APPROVED** [review]
Thanks @t1m0thyj I will approve so if it does work fine on this branch we can push the release, we just need to make sure it gets ported back into main

**Comment by t1m0thyj** [comment]
> Thanks @t1m0thyj I will approve so if it does work fine on this branch we can push the release, we just need to make sure it gets ported back into main

@JillieBeanSim We shouldn't need to port this change to the main branch, as it only applies to prerelease versions and we're only doing those on the `release/3.*` branch.

**Comment by JillieBeanSim** [comment]
thanks it'll have to be on main for the next release/3.* branch created, but not worries I will create a port PR after deployment to push updated CHANGELOGs back with release tag in them

**Pull request merged**
