### PR TITLE
fix(v3): Fix sessions disappearing from trees caused by `zowe.extRefresh`

### LINKED ISSUE #2906: Updating credentials empties all tree views in the Activity Bar
**Describe the bug**

In the latest version of Zowe Explorer, updating credentials on a profile causes all of the profile nodes to disappear from the tree view.

The only workaround I've found thus far is to reload the window (hence, restarting VS Code also works). If I try to add a profile back to the tree prior to doing so, nothing happens.

**To Reproduce**

1. Right-click on a profile node in the tree view
2. Select "Manage Profile" -> "Update Credentials"
3. Type in the new credentials for the profile
4. Notice that after entering the password and pressing the 'Enter' key, the "credential update" message shows, but all of the profiles have been removed from the tree

**Expected behavior**

Profiles should not be removed from the tree view after updating credentials for a specific profile.

**Screenshots**

ZE-Update-Creds-Bug

**Desktop (please complete the following information):**

- OS: Windows 10 22H2
- Zowe Explorer Version: 2.15.4
- (Optional) Zowe CLI Version: N/A
- (Optional) Are you using Secure Credential Store? Yes

### PR DESCRIPTION
**Pull request by t1m0thyj**
## Proposed changes

Fixes #2906 

## Release Notes

Milestone: v3

Changelog: Fixed issue where creating new team configuration file could cause Zowe Explorer to crash, resulting in all sessions disappearing from trees

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [ ] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [ ] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [ ] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

**Review by traeok — CHANGES_REQUESTED** [review]
Thanks for looking into this @t1m0thyj.
I'm running into an issue with this branch that I cannot reproduce in `next`:

1. Set up a direct-to-service LPAR in the Data Sets tree that has the correct user and password stored securely
2. Right-click on the profile and select "Manage Profile" -> "Update Credentials"
3. Enter in the username and press enter.
4. Press Escape to exit this menu.
5. Right-click on the profile again and select "Manage Profile." Notice that the option now says "Add Credentials" instead of "Update Credentials" (I'm also seeing this on `next`)
6. Click on "Add Credentials". Enter in your username and press enter.
7. Enter in an invalid password and press enter.
8. Notice that credentials were updated. Try to perform a search with this profile to encounter the "Update Credentials" prompt.
9. Update your credentials using the correct username and password.
10. Try to execute the search again. Notice that the search still fails with the invalid credentials error, even though the correct credentials were entered.

**Review by anaxceron — DISMISSED** [review]
One minor comment, but otherwise this looks dandy.

**Review by traeok — APPROVED** [review]
I was able to confirm that there was an issue with my Zowe team config's secure array. After resetting my config file and preparing my environment, I was unable to reproduce the previous scenario I encountered. 

LGTM, thanks Timothy!

**Review by traeok — DISMISSED** [review]

**Review by zFernand0 — DISMISSED** [review]
LGTM! 😋 
I'm guessing it's ok for this port-PR to be merged before the V2 one since we don't need to verify Theia support for V3? 😋

**Review by anaxceron — APPROVED** [review]
Nice!

**Review by zFernand0 — APPROVED** [review]

**Review by awharn — APPROVED** [review]

**Review by zFernand0 — APPROVED** [review]

**Review by traeok — APPROVED** [review]
I started reviewing this one first and ended up approving the v2 one - oops 😅 

LGTM, thanks Timothy!

**Pull request merged**
