### PR TITLE
feat: 'Copy Relative Path' for USS, 'Copy Name' for DS & Jobs

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

Implements three features:
- "Copy Relative Path" for USS files and directories
  - "relative" meaning relative to the search filter that's been set on the profile node. For example, if the full path for a file is `/z/testUser/file.txt` and the search filter is set to `/z/testUser`, it will return "file.txt"
- "Copy Name" for DS, PDS, PDS members and migrated DS
  - PDS members will return the format `SOME.PDS(MEMNAME)`
- "Copy Name" for jobs and spool files
  - Currently this just returns the label of the node, we can enhance this in the future if needed. Most of the interest was expressed for USS and DS

## Release Notes

Milestone: 2.17.0

Changelog:

- Added a "Copy Relative Path" context option for USS files and directories in the tree view. [#2908](https://github.com/zowe/zowe-explorer-vscode/pull/2908)
- Added a "Copy Name" context option for data sets, jobs and spool files in the tree view. [#2908](https://github.com/zowe/zowe-explorer-vscode/pull/2908)

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found

### CODE REVIEW

**Review by anaxceron — DISMISSED** [review]
Looks good, thanks @traeok

**Review by zFernand0 — DISMISSED** [review]
Love the enhancement! 🙏🏽
Curious if we can limit the Job label to just the `Jobname(Jobid)` (instead of the `name(id) - SYSTEM | ACTIVE [ - CC ]`) 😅 

I'm still approving because I agree that this can be enhanced in the future 😋 

LGTM! 😋

**Comment by traeok** [comment]
> Love the enhancement! 🙏🏽 Curious if we can limit the Job label to just the `Jobname(Jobid)` (instead of the `name(id) - SYSTEM | ACTIVE [ - CC ]`) 😅

Thanks for the suggestion! I've pushed up commit 23e66bc that will return that format for jobs with valid job objects 😋

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋 

---

Thanks for addressing the feedback so quickly! 🥳 

For spool-files, I don't think people will need the job name or id to be there as prefix 😋 
I think just having JES:JESMSGLG is probably more than enough 😋

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks @traeok!

**Pull request merged**
