### PR TITLE
[v3 port] fix: optimize `ProfilesCache.checkMergingConfigAllProfiles` and fix type error

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

This ports the changes from #2771 into v3 (only the ProfilesCache changes, as we won't need the separator checks for v3)

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by traeok** [comment]
I haven't added a changelog entry since the changes from 2.15 will eventually be merged into next - once those changes are merged, the changelog entry will be there 🙂

**Review by t1m0thyj — APPROVED** [review]

**Review by zFernand0 — COMMENTED** [review]
waiting for the other PR to be merged.
Also, should we have a changelog here?
Last, but not least... I guess we don't need to filter possible undefined quick-pick separators, do we?

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋 
Q: do we need to port over the changes in `packages/zowe-explorer/src/utils/LoggerUtils.ts`?

**Comment by traeok** [comment]
> Q: do we need to port over the changes in `packages/zowe-explorer/src/utils/LoggerUtils.ts`?

No need - since we have a more recent engine version for v3 we can expect the original logic to work as intended 🙂

**Pull request merged**
