### PR TITLE
fix(v3): Fix ZE V3 failing to load after upgrading from V1 

### LINKED ISSUE #3046: ZE V3 fails to load after upgrading from V1 until window is reloaded
**Describe the bug**

After upgrading from ZE V1 to V3, if you select "Restart Extensions" to restart the VS Code extension host, then ZE fails to load until the window is reloaded.

**To Reproduce**

1. Install Zowe Explorer V1 in VS Code
2. Update to a V3 prerelease VSIX
3. Select "Restart Extensions" when prompted by VS Code
4. Notice that ZE fails to load

**Expected behavior**

After reloading the VS Code window (or closing and relaunching the application), then ZE V3 works fine. I would expect "Restart Extensions" to behave the same way.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 11
- Zowe Explorer Version: V3

**Additional context**

Thanks @gejohnston for reporting this 😋

### PR DESCRIPTION
**Pull request by t1m0thyj**
## Proposed changes

Fixes #3046 

## Release Notes

Milestone:

Changelog:

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [ ] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [ ] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [ ] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

**Comment by traeok** [comment]
Marking as draft to resolve another convert v1 issue: the "Create New" option does not work as tree is not yet initialized

**Review by JillieBeanSim — APPROVED** [review]
LGTM! tested all 3 options, cancel, create new and convert and all worked as expected.  Thanks @t1m0thyj

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋 

We should refer back to this PR in case we come across new breaking behavior from VSCode 😋 

Smart way to work around the `Refresh Extensions` button. And thanks for leaving the comment in the code 😋

**Comment by zFernand0** [comment]
Audit should be fixed on the next sdk-update 😋

**Pull request merged**
