### PR TITLE
Fix issue where USS files can't be submitted as JCL

### PR DESCRIPTION
**Pull request by t1m0thyj**
## Proposed changes

Fixes invalid logic for getting profile name of USS path and replaces it with code that matches vNext behavior

## Release Notes

Milestone: 2.16.3?

Changelog: Fixed issue where USS files could not be submitted as JCL

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [ ] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [ ] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [ ] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @t1m0thyj 

Do we want to update lerna to go ahead and publish with this branch merge or do that separately?

**Review by JillieBeanSim — APPROVED** [review]

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋

**Comment by zFernand0** [comment]
I believe we would want to port this over to vNext 😋 
👀 @t1m0thyj 
👀 @traeok

**Comment by t1m0thyj** [comment]
> I believe we would want to port this over to vNext 😋 👀 @t1m0thyj 👀 @traeok

Discussed with @traeok and this is already fixed in vNext. Thanks for staying on top of this 😋

**Pull request merged**
