### PR TITLE
Add missing held status option

### PR DESCRIPTION
**Pull request by rudyflores**
## Proposed changes

Solves #2452 
Add missing status option `held` for job owner/prefix search

## Release Notes

Milestone: 2.11.0

Changelog: Added missing status held option for job searches

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

Screenshot 2023-09-08 at 12 52 47 PM

### CODE REVIEW

**Review by traeok — APPROVED** [review]
LGTM, thanks @rudyflores

**Review by JillieBeanSim — COMMENTED** [review]
Hey @rudyflores is there support for zosmf profiles in the Zowe CLI for a status filter of `Held`?  I know Kristina did work on the Zowe CLI side for the other status filters in her [PR](https://github.com/zowe/vscode-extension-for-zowe/pull/2009/files) that also brought in the updated cli dependency with her contributions.

**Comment by rudyflores** [comment]
> Hey @rudyflores is there support for zosmf profiles in the Zowe CLI for a status filter of `Held`? I know Kristina did work on the Zowe CLI side for the other status filters in her [PR](https://github.com/zowe/vscode-extension-for-zowe/pull/2009/files) that also brought in the updated cli dependency with her contributions.

Make sense, I think the change will have to be made on the Zowe CLI side of things before we go ahead and merge this change in order to have support on z/OSMF profiles for this

**Comment by traeok** [comment]
> Is there support for zosmf profiles in the Zowe CLI for a status filter of `Held`? I know Kristina did work on the Zowe CLI side for the other status filters in her [PR](https://github.com/zowe/vscode-extension-for-zowe/pull/2009/files) that also brought in the updated cli dependency with her contributions.

@JillieBeanSim @rudyflores By "support for zosmf profiles," does this refer to support within the jobs SDK? As far as I'm aware, we should support the "held" status, as we pass it as a query parameter to `GetJobs.getJobsByParameters`. Then we filter the response based on job status: https://github.com/zowe/zowe-cli/blob/cc2aaa66006037aa4022d2ca4fa4bc6ea44a49da/packages/zosjobs/src/GetJobs.ts#L221

**Comment by rudyflores** [comment]
> 

Were you able to view jobs under `HELD` if you tried to use the filter on your end?

**Comment by traeok** [comment]
> Make sense, I think the change will have to be made on the Zowe CLI side of things before we go ahead and merge this change in order to have support on z/OSMF profiles for this

@rudyflores Turns out that while the logic _would_ work here for filtering by "held" status, z/OSMF API does not support returning the "held" status. It only returns one of three values: "INPUT", "ACTIVE", "OUTPUT".

Here is the link to the z/OSMF enhancement request:

https://ibm-z-hardware-and-operating-systems.ideas.ibm.com/ideas/ZOS-I-3349

Once this enhancement is implemented, this functionality would work without any changes to Zowe CLI, as the CLI filters the job list based on the status provided to `getJobsByParameters`.

**Review by t1m0thyj — CHANGES_REQUESTED** [review]
I would like for this functionality to be added in Zowe Explorer to filter jobs by Held status 🙂 
However I'm afraid we can't support it until z/OSMF is enhanced to return this status as @traeok mentioned 😢

**Comment by rudyflores** [comment]
Switching this PR to draft until the z/OSMF enhancement is addressed

**Comment by JillieBeanSim** [comment]
with no activity on this for almost a year and being really out of date can this be closed? @zFernand0 @rudyflores @adam-wolfe

**Comment by rudyflores** [comment]
@JillieBeanSim I believe this can be closed for now, I remember the issue was with z/OSMF not having support for this yet and we were not sure when they planned on adding support for it. So for now let's close and we can re-evaluate once this is addressed on the z/OSMF side of things

**Pull request closed without merging**
