### PR TITLE
fix(v2): Toggle off Auto Save and warn user after save error

### LINKED ISSUE #2406: Repeated attempt to save member despite S913
**Description of problem**

**Zowe Extension user edits a read-only dataset, and hits save -- system log shows continual attempts to save the update, despite incurring S913 abends

Results in pages and pages of log entries like:

```
 ICH408I USER(Zxxxxx  ) GROUP(STUDENT2) NAME(####################) 605      
   ZXP.PUBLIC.JCL CL(DATASET ) VOL(VPWRKD)                                  
   INSUFFICIENT ACCESS AUTHORITY                                            
   FROM ZXP.PUBLIC.** (G)                                                   
   ACCESS INTENT(UPDATE )  ACCESS ALLOWED(READ   )                          
 IEC150I 913-38,IFG0194E,Zxxxxx,IZUFPROC,SYS00328,0D33,VPWRKD, 606          
 ZXP.PUBLIC.JCL(REPRO)                                                      
 ICH408I USER(Zxxxxx  ) GROUP(STUDENT2) NAME(####################) 607      
   ZXP.PUBLIC.JCL CL(DATASET ) VOL(VPWRKD)                                  
   INSUFFICIENT ACCESS AUTHORITY                                            
   FROM ZXP.PUBLIC.** (G)                                                   
   ACCESS INTENT(UPDATE )  ACCESS ALLOWED(READ   )                          
 IEC150I 913-38,IFG0194E,Zxxxxx,IZUFPROC,SYS00330,0D33,VPWRKD, 608          
 ZXP.PUBLIC.JCL(REPRO)                                                      
 ICH408I USER(Zxxxxx  ) GROUP(STUDENT2) NAME(####################) 609      
   ZXP.PUBLIC.JCL CL(DATASET ) VOL(VPWRKD)                                  
   INSUFFICIENT ACCESS AUTHORITY                                            
   FROM ZXP.PUBLIC.** (G)                                                   
   ACCESS INTENT(UPDATE )  ACCESS ALLOWED(READ   )                          
 IEC150I 913-38,IFG0194E,Zxxxxx,IZUFPROC,SYS00332,0D33,VPWRKD, 610          
 ZXP.PUBLIC.JCL(REPRO)                                                      
 ICH408I USER(Zxxxxx  ) GROUP(STUDENT2) NAME(####################) 611      
   ZXP.PUBLIC.JCL CL(DATASET ) VOL(VPWRKD)                                  
   INSUFFICIENT ACCESS AUTHORITY                                            
   FROM ZXP.PUBLIC.** (G)                                                   
   ACCESS INTENT(UPDATE )  ACCESS ALLOWED(READ   )                          
 IEC150I 913-38,IFG0194E,Zxxxxx,IZUFPROC,SYS00334,0D33,VPWRKD, 612          
 ZXP.PUBLIC.JCL(REPRO)                                                      
 ICH408I USER(Zxxxxx  ) GROUP(STUDENT2) NAME(####################) 613      
   ZXP.PUBLIC.JCL CL(DATASET ) VOL(VPWRKD)                                  
   INSUFFICIENT ACCESS AUTHORITY                                            
   FROM ZXP.PUBLIC.** (G)                                                   
   ACCESS INTENT(UPDATE )  ACCESS ALLOWED(READ   )                          
 IEC150I 913-38,IFG0194E,Zxxxxx,IZUFPROC,SYS00336,0D33,VPWRKD, 614          
 ZXP.PUBLIC.JCL(REPRO)                                                      
 ICH408I USER(Zxxxxx  ) GROUP(STUDENT2) NAME(####################) 615      
   ZXP.PUBLIC.JCL CL(DATASET ) VOL(VPWRKD)                                  
   INSUFFICIENT ACCESS AUTHORITY                                            
   FROM ZXP.PUBLIC.** (G)                                                   
   ACCESS INTENT(UPDATE )  ACCESS ALLOWED(READ   )                          
 IEC150I 913-38,IFG0194E,Zxxxxx,IZUFPROC,SYS00338,0D33,VPWRKD, 616          
 ZXP.PUBLIC.JCL(REPRO)                                                      
******************************************************************************
```
with each entry appears 1-3 seconds apart.

**Reproduce Error**

**In VSCode/ZOWE Extension, Open SYS1.MACLIB (be sure you don't have WRITE access!) open ABEND, make arbitrary update, and save (cmd-/ctrl-S, or file->save)**

**Expected behavior**

** Single attempt to write to dataset - note S913 and stop any further attempt to save **

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows and MacOS
- Zowe Explorer Version: 2.9.*
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

Fixes #2406, #2627 

**Error message shown when Auto Save is enabled:**
image

### How to test

- Locate a UNIX file or data set with insufficient write permissions.
- Open this resource in Zowe Explorer.
- Enable Auto Save and make changes to the file
- Notice that when the save error occurs, the document is marked unsaved and no more save requests are made. Notice that Auto Save is also disabled.
  - Try enabling the Auto Save feature using either the "Enable Auto Save" option in this dialog, or by using the Command Palette -> "Files: Toggle Auto Save". The process will repeat at this point, but the save request will only happen once.

When Auto Save is used with v2.18.0, save requests were continuously added for each data set and file that failed to save. Even if you would try to close the file or dismiss the error, another request would be added, and a reload of VS Code was necessary to stop the loop.

## Release Notes

Milestone: 2.18.1

Changelog:

- Fixed an issue when Auto Save is enabled where a failed UNIX file or data set save operation resulted in an indefinite loop of additional save requests. [#2406](https://github.com/zowe/zowe-explorer-vscode/issues/2406), [#2627](https://github.com/zowe/zowe-explorer-vscode/issues/2627)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] All PR dependencies have been merged and published (if applicable)
- [x] A GIF or screenshot is included in the PR for visual changes
- [x] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [x] There is coverage for the code that I have added
- [x] I have added new test cases and they are passing
- [x] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks for this fix @traeok

**Review by JillieBeanSim — APPROVED** [review]

**Review by zFernand0 — DISMISSED** [review]
I was a bit confused when I saw the `localize` function but then realized this was for V2 😋 

LGTM! 🙏

**Review by zFernand0 — APPROVED** [review]
still LGTM! 😋 
thanks for adding the extra test 🙏

**Review by JillieBeanSim — APPROVED** [review]
still LGTM! thanks @traeok

**Pull request merged**
