### PR TITLE
Final v3 prerelease

### PR DESCRIPTION
**Pull request by JillieBeanSim**
## Proposed changes

Prepare final v3 pre-release

Waiting on these PRs:

- https://github.com/zowe/zowe-explorer-vscode/pull/3133
- https://github.com/zowe/zowe-explorer-vscode/pull/3129
- https://github.com/zowe/zowe-explorer-vscode/pull/3127
- https://github.com/zowe/zowe-explorer-vscode/pull/3130
- https://github.com/zowe/zowe-explorer-vscode/pull/3135 
- https://github.com/zowe/zowe-explorer-vscode/pull/3111

## Release Notes

Milestone: v3 pre-release

Changelog: n/a

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [ ] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [ ] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [ ] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

### CODE REVIEW

**Comment by adam-wolfe** [comment]
We should also resolve the member node credential desync https://github.com/zowe/zowe-explorer-vscode/pull/3111.

**Comment by JillieBeanSim** [comment]
> We should also resolve the member node credential desync #3111.

Do we have an eta for this @t1m0thyj?

It would be good to get last pre-release out by EOD tomorrow (9/23) with fixes requested from extenders and rest of fixes can be included in 3.0 GA or 3.0.1 patch

**Comment by t1m0thyj** [comment]
@JillieBeanSim The port PR (#3135) is ready for review 😋  Planning to wrap up tests on the other PR (#3111) by EoD today.

**Comment by zFernand0** [comment]
Just to clarify, was the decision to test and merge https://github.com/zowe/zowe-explorer-vscode/pull/3149 in replacement of https://github.com/zowe/zowe-explorer-vscode/pull/3147?

**Comment by JillieBeanSim** [comment]
Hey all, can we get the following PRs reviewed early Wed, 9/25, and possibly get this pre-release out possibly by lunch? @zFernand0 @t1m0thyj @traeok @likhithanimma1 @awharn @SanthoshiBoyina1 and @adam-wolfe 
- https://github.com/zowe/zowe-explorer-vscode/pull/3111
- https://github.com/zowe/zowe-explorer-vscode/pull/3148

once merged I can update the release branches, if the PR have CHANGELOGs we can expect merge conflicts 😄 Thanks all!

**Review by zFernand0 — DISMISSED** [review]
Remaining PRs are just waiting on reviews.
For now... this PR LTGM! 😋

**Comment by t1m0thyj** [comment]
> Q: do we want to wait for the resolution of this comment?
> 
> * [Fix credentials not refreshed in ds tree and misc profile related fixes #3111 (review)](https://github.com/zowe/zowe-explorer-vscode/pull/3111#pullrequestreview-2328128198)

I'm investigating a fix for that now, but as it's more of an edge case I don't think it should hold up this prerelease 😋

**Review by adam-wolfe — APPROVED** [review]

**Review by likhithanimma1 — APPROVED** [review]

**Pull request merged**
