### PR TITLE
Fix #2484: Added Status bar to indicate data is being pulled from mainframe.

### LINKED ISSUE #2484: No UI indicator presented to end user after clicking "Pull from Mainframe"
**Describe the bug**

There is no indication that the "Pull from Mainframe" action is ongoing once a user clicks it. We should show some sort of indication, such as a status bar indicator, to keep end users up to date.

**To Reproduce**

1. Search for a data set
2. Right-click on a data set member -> "Pull from Mainframe"
3. Notice that no UI indicator appears.

**Expected behavior**

Users should see some indication that we are actively pulling data from the mainframe.

### PR DESCRIPTION
**Pull request by Ash-2k3**
## Proposed changes

This PR addresses issue https://github.com/zowe/zowe-explorer-vscode/issues/2484.  I began by searching the codebase for the string "Pull from Mainframe" and found the associated keys "refreshDataset", "uss.refreshUSS", and "jobs.refreshSpool". This led me to the relevant code sections, where I determined that these keys trigger commands responsible for pulling data from the mainframe in different contexts. I added status bar indicators within the corresponding command handlers in the init.ts file to provide users with visual feedback during "Pull from Mainframe" operations.

## Release Notes

Milestone:

Changelog: Added Status bar to indicate that data is being pulled from mainframe.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by t1m0thyj** [comment]
> One test is failing and I am not sure how it's supposed to fix. (https://github.com/zowe/zowe-explorer-vscode/actions/runs/8784312920/job/24102290328?pr=2865)
> 
> Is it related to filling up the changelog section of Release Notes ?

@Ash-2k3 Yes, please add a line to [the changelog](https://github.com/zowe/zowe-explorer-vscode/blob/main/packages/zowe-explorer/CHANGELOG.md) in the "TBD Release > Bug Fixes" section and include a link to the issue number 🙂

**Comment by Ash-2k3** [comment]
I have added a line to the "TBD release > New features and enhancements" section for now. Please lmk if it needs to be changed, Thanks :)

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋 
Love the clean implementation too 🥳

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @Ash-2k3 for this addition ❤️

**Pull request merged**
