### PR TITLE
deps: update Zowe CLI to 7.23.6 to pull in Imperative bug fixes

### LINKED ISSUE #2773: zowe.schema.json is not updated automatically when extenders contribute a new service profile to zowe-explorer-api
**Describe the bug**

When extenders use zowe-explorer-api to contribute a new service profile, any currently present zowe.schema.json files (either workspace/global level) do not get updated to contain the new service profile's metadata. Currently, the only way to update the schema is by creating a new team configuration file using the Zowe Explorer views.

**To Reproduce**

1. Make sure a zowe schema and team configuration files are already present at either workspace or global level
2. Create an extender that registers a new service profile type with zowe-explorer-api using ApiExplorerExtender.initForZowe() and ProfilesCache.registerCustomProfilesType().
3. Call ApiExplorerExtender.reloadProfiles()
4. Without creating a new team configuration file, try and add the new service profile defined in step 2 in the existing team configuration file.

**Expected behavior**

The newly added service profile should not introduce syntax errors in the team configuration file and should continue to function.

**Actual behavior**

The zowe team config file will not recognize the profile type since the zowe.schema.json is never updated, introducing syntax errors. ProfilesCache will also fail to load these newly defined profiles.

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version: Zowe-explorer-api v2.14.1
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

Resolves #2773 
Updates the Zowe CLI dependency, resolving an issue that surfaced from Imperative's `ProfileInfo` class.

## Release Notes

Milestone: 2.15.1

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by traeok** [comment]
Note that in the most recent commit (a21d708) I've removed Node 14 from the pipelines so that it supports the updated dependencies in Imperative.

Here's why I feel that it should be okay to remove Node 14 from the matrix:
- The VS Code team recommends using at least Node 16 to build extensions for recent versions of VS Code - [see here for more info](https://github.com/microsoft/vscode-l10n/issues/114#issue-1746296958)
- The latest version of VS Code uses Node 18
- The oldest version of VS Code that we claim to support (1.53.2) uses Node 12, but I was able to build the extension using Node 16 (or even Node 18) and used it without issue

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks @traeok!

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋 
just waiting on others to review before merging 🥳

**Review by JillieBeanSim — COMMENTED** [review]
Hey @traeok thanks this looks good to me, are we planning a patch release with this update and has it already been updated on main?  I ask since we were just publishing from maintenance and developing against main & next.

**Pull request merged**
